server:
  port: 8093
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.222.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    
    #配置springmvc试图解析器
    
  mvc:         #引入mvn配置
    view:
      prefix: /WEB-INF/views/ # /默认代表根目录 src/main/webapp
      suffix: .jsp


#SpringBoot整合Mybatis-plus   使用时切记使用模式不同

mybatis-plus:
   #定义别名包 当程序自动映射时自动拼接
  type-aliases-package: com.jt.pojo
  #必修编辑映射文件中编辑sql
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
    
#以下配置是dubbo的    
dubbo:
  scan:
    basePackages: com.jt  #包扫描
  application:
    name: provider-user  #定义服务的名称
  registry:              #链接zk
    address: zookeeper://192.168.222.128:2181
  protocol:    
    name: dubbo
    port: 20880    #表示duboo内部的通信端口    
    
#引入log日志
logging:
  levlel:
       #扫描包的路径
        com.jt.mapper: debug